module.exports = {
  Env: 'It will be rewritten by process.env.NODE_CONFIG_ENV or process.env.NODE_ENV',
  Tags: [],
  Datawich: {
    configVersion: '0.0.0',
    logsDir: '/data/logs/datawich',
    wecomBotKey: '',
    adminPort_frontend: 3299,
    adminPort_frontend2: 3298,
    adminBaseURL: 'http://localhost:3298,http://localhost:3299',
    adminPort: 3300,
    adminJwtSecret: '<Datawich Random 32>',
    webPort_frontend: 3303,
    webBaseURL: 'http://localhost:3304',
    webPort: 3304,
    webJwtSecret: '<Datawich Random 32>',
    webSSO: {
      baseURL: 'https://sso.staging.fangcha.net',
      clientId: '<clientId>',
      clientSecret: '<clientSecret>',
      authorizePath: '/api/v1/oauth/authorize',
      tokenPath: '/api/v1/oauth/token',
      logoutPath: '/api/v1/logout',
      scope: 'basic',
      callbackUri: 'http://localhost:3304/api/v1/handleSSO',
      userInfoURL: 'https://sso.staging.fangcha.net/api/v1/oauth/user-info',
    },
    openPort: 3200,
    openBaseURL: 'http://localhost:3200',
    adminSSO: {
      baseURL: 'https://sso.staging.fangcha.net',
      clientId: '<clientId>',
      clientSecret: '<clientSecret>',
      authorizePath: '/api/v1/oauth/authorize',
      tokenPath: '/api/v1/oauth/token',
      logoutPath: '/api/v1/logout',
      scope: 'basic',
      callbackUri: 'http://localhost:3298/api/v1/handleSSO',
      userInfoURL: 'https://sso.staging.fangcha.net/api/v1/oauth/user-info',
    },
    superAdminEmail: '<superAdminEmail>',
    mysql: {
      datawichDB: {
        host: '127.0.0.1',
        port: 3306,
        database: 'datawich',
        username: 'root',
        password: '',
        dialect: 'mysql',
        timezone: '+08:00',
        logging: false,
      },
    },
    useResque: false,
    useSchedule: false,
    datawichResque: {
      redisHost: '127.0.0.1',
      redisPort: 30200,
      dynamicQueues: [],
    },
    frontendConfig: {
      // colorPrimary: 'rgb(221 115 164)',
      appName: 'Datawich 🍰',
      colorPrimary: '#DD73A4',
      ossParams: {
        defaultBucketName: 'fc-web-oss',
        defaultOssZone: 'datawich',
      },
    },
    datawichDownloadDir: '/data/datawich-zone/downloads',
    ossOptions: {
      Default: {
        visitor: {
          region: 'oss-cn-shanghai',
          accessKeyId: '__accessKeyId__',
          accessKeySecret: '<OSS accessKeySecret>',
          bucket: '__bucket__',
          secure: true,
        },
        uploader: {
          region: 'oss-cn-shanghai',
          accessKeyId: '__accessKeyId__',
          accessKeySecret: '<OSS accessKeySecret>',
          bucket: '__bucket__',
          secure: true,
        },
        uploadSignature: {
          accessKeyId: '__accessKeyId__',
          accessKeySecret: '<OSS accessKeySecret>',
          bucketURL: '<bucketURL>',
          timeout: 3000,
        },
        remoteRootDir: 'datawich-staging',
        downloadRootDir: '/data/datawich-zone/downloads',
      },
    },
  },
}
